name: testing

on:
  push:

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: update changes
        run: |
          openssl rand -hex 16 > test.txt

      - name: git push changes
        uses: appleboy/git-push-action@v0.0.2
        with:
          author_email: teabot@gitea.io
          author_name: GiteaBot
          branch: main
          commit: true
          commit_message: "[skip ci] Updated changes by gitea bot"
          remote: git@github.com:appleboy/git-push-action.git
          ssh_key: ${{ secrets.DEPLOY_KEY }}
